### ISSUE TITLE
Exercise 14, issue with tests

### ISSUE THREAD

**Issue by jferragut** [4GeeksAcademy/javascript-arrays-exercises-tutorial#11]
Given the following function:

```javascript
function mergeTwoList(arr){
    let even = [];
    let odd = [];
    for(let i=0; i<list_of_numbers.length; i++){
        if(list_of_numbers[i]%2===0){
            even.push(list_of_numbers[i]);
        }else{
            odd.push(list_of_numbers[i]);
        }
    }
    return odd.concat(even);
}
```
When you build, the answers and lengths match expected result perfectly. Tests 3 to 5, however, are failing. 

I took a look at the unit tests themselves and they appear to be written correctly and with no issues. 

This may be an issue with learnpack compilation/testing.

**Comment by jferragut** [comment]
@alesanchezr this was the issue I mentioned yesterday.

**Comment by tommygonzaleza** [comment]
The test is working fine, the problem is that in your code you are using the name of the array instead of the parameter, so when the test do the mock of the function and try it with another array, is giving the incorrect output.
