### ISSUE TITLE
Array exercise 

### ISSUE THREAD

**Issue by soyeltigre24** [4GeeksAcademy/javascript-arrays-exercises-tutorial#9]
i keep on on getting the same issue when i want to work on JS.. 

![Screen Shot 2021-02-10 at 12 41 08 PM](https://user-images.githubusercontent.com/77759754/107549013-53820700-6b9d-11eb-8687-8c4774a76e2e.png)

**Comment by alesanchezr** [comment]
Are you in the 4Geeks Slack channel? Can you send me a private message??
